export const restApiEndpointOutputKey = 'RestApiEndpoint'
export const userPoolClientIdOutputKey = 'UserPoolClientId'
export const userPoolIdOutputKey = 'UserPoolId'
export const testAcceptedEmailDomain = 'test.co'
export const testAdminEmail = 'test@test.co'
export const testAdminPassword = 'testT3$t'
export const testAutoConfirmedEmail = 'korwin.miler@fake.com'