name: Build Prod

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  build:
    name: Build Prod Job
    runs-on: ubuntu-latest
    env:
      CDK_STACK_NAME: prod-AkuratAuthStack
      CDK_DIFF_OUT_FILE: diff.out
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Unit tests
        run: |
          npm test

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_KEY }}
          aws-region: eu-central-1

      - name: AWS CDK synth
        run: |
          cdk synth ${{ env.CDK_STACK_NAME }} --context domainName=${{ secrets.DOMAIN_NAME }} 

      - name: AWS CDK diff
        run: |
          cdk diff ${{ env.CDK_STACK_NAME }} --ci --context domainName=${{ secrets.DOMAIN_NAME }} >> ${{ env.CDK_DIFF_OUT_FILE }}

      - name: Add PR comment with diff result
        uses: actions/github-script@v6
        with:
          script: |
            var fs = require('fs')
            const diff = fs.readFileSync('${{ env.CDK_DIFF_OUT_FILE }}').toString().trimEnd()
            const output = ['👋 Below you find the result of running the command on the \`${{ env.CDK_STACK_NAME }}\` AWS CDK Stack']
            output.push(['<details><summary>AWS CDK diff</summary>\n\n\`\`\`\n' + diff + '\n\`\`\`\n</details>\n'])
            output.push([`*Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`])
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output.join('\n')
            })

      - name: Archive AWS CDK diff outputs
        uses: actions/upload-artifact@v3
        with:
          name: cdk-diff-outputs
          path: ${{ env.CDK_DIFF_OUT_FILE }}